version: '3'

services:
  linux:
    image: golang:1.13
    working_dir: /go/src/
    volumes:
      - $PWD:/go/src
      - $PWD/rootfs:/rootfs
      - $PWD/ubuntu_rootfs:/ubuntu_rootfs
    privileged: true
    command: /bin/bash
